# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Focus < Formula
  desc "A minimalist pomodoro timer"
  homepage "https://github.com/nendix/focus"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nendix/focus/releases/download/v1.0.3/focus_Darwin_x86_64.tar.gz"
      sha256 "e98456a610afb5b874751d179b98016be8a8b18e84b62f18db0be8af13090d25"

      define_method(:install) do
        bin.install "focus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nendix/focus/releases/download/v1.0.3/focus_Darwin_arm64.tar.gz"
      sha256 "abc0f705a57d2e6e1db23aaddec2ff85512a2d97fec863c40056a0ce1f014faa"

      define_method(:install) do
        bin.install "focus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nendix/focus/releases/download/v1.0.3/focus_Linux_x86_64.tar.gz"
      sha256 "fe59b869f018671b10cedcdd87c3b6d9b805ced166dfbfb4534286446dec6bb5"
      define_method(:install) do
        bin.install "focus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nendix/focus/releases/download/v1.0.3/focus_Linux_arm64.tar.gz"
      sha256 "ba83f8add0440d21b95df6997e2db0e019cf3f72becc6934e90585091650fdff"
      define_method(:install) do
        bin.install "focus"
      end
    end
  end
end
