# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiart < Formula
  desc "A blazing fast CLI tool to convert images to high-res ASCII art."
  homepage "https://github.com/nendix/kiart"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nendix/kiart/releases/download/v0.1.1/kiart_Darwin_x86_64.tar.gz"
      sha256 "913313a626f18e970eba3b7705f4a145dcd263d0115961673b6ef8c9916922fd"

      define_method(:install) do
        bin.install "kiart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nendix/kiart/releases/download/v0.1.1/kiart_Darwin_arm64.tar.gz"
      sha256 "bbb635e7dcfa8f6e767b8787567f39438e71200f6be9aa6fef69ff454a059e8b"

      define_method(:install) do
        bin.install "kiart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nendix/kiart/releases/download/v0.1.1/kiart_Linux_x86_64.tar.gz"
      sha256 "7a556e389b2cc1aaca435b270fef63f8882bff326cb237a9d4dfdb244166c5c9"
      define_method(:install) do
        bin.install "kiart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nendix/kiart/releases/download/v0.1.1/kiart_Linux_arm64.tar.gz"
      sha256 "406d4c89e1584a1b64823070efba3a5c6106b2ce7406afd113855f82dc00fa6e"
      define_method(:install) do
        bin.install "kiart"
      end
    end
  end
end
